# 複製此檔案為 .streamlit/secrets.toml 並填入你的 API 金鑰
OPENROUTER_API_KEY = "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"
ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/22751393/2pjou6u/" 