# 複製此檔案為 .streamlit/secrets.toml 並填入你的 API 金鑰
OPENROUTER_API_KEY = "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"
ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/22751393/2pjou6u/" 
