# 複製此檔案為 .streamlit/secrets.toml 並填入你的 API 金鑰
OPENROUTER_API_KEY = "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"
ZAPIER_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/22751393/2pjou6u/" 